#!/usr/bin/tcsh 

module purge
module use /cvmfs/oasis.opensciencegrid.org/jlab/scicomp/sw/el9/modulefiles
module load root/6.30.04-gcc11.4.0

set sf_flag=`awk '/SF model flag/ {print $1; exit}' infiles/$1.inp`
if ( "$sf_flag" == "1" ) then
  set suffix="3HeFit"
else
  set suffix=""
endif
set mc_tag="${1}${suffix}"

cd src
make clean
make
./mc_single_arm <<EOF |& tee "../runout/$1.out"
$1
EOF
cd ../util/root_tree
make clean
make
./make_root_tree << endofinput
$mc_tag
endofinput
cd ../..
rm -f worksim/$mc_tag.bin
mv worksim/$mc_tag.root outfiles/$mc_tag.root
